# Form implementation generated from reading ui file 'AddBook.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc

my_db = mc.connect(
    host='localhost',
    user='root',
    password='',
    database='library'
)
mycursor = my_db.cursor()

class Add_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_title = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_title.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_title.setFont(font)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.verticalLayout.addWidget(self.lineEdit_title)
        self.lineEdit_author = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_author.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_author.setFont(font)
        self.lineEdit_author.setObjectName("lineEdit_author")
        self.verticalLayout.addWidget(self.lineEdit_author)
        self.lineEdit_publisher = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_publisher.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_publisher.setFont(font)
        self.lineEdit_publisher.setObjectName("lineEdit_publisher")
        self.verticalLayout.addWidget(self.lineEdit_publisher)
        self.pushButton_insertbook = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_insertbook.setFont(font)
        self.pushButton_insertbook.setStyleSheet("""QPushButton {
background-color:gray;
color:white
}""")

        #adding method
        self.pushButton_insertbook.clicked.connect(self.insert_book)

        self.pushButton_insertbook.setObjectName("pushButton_insertbook")
        self.verticalLayout.addWidget(self.pushButton_insertbook)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Book"))
        self.lineEdit_title.setPlaceholderText(_translate("Dialog", "Please Enter Title"))
        self.lineEdit_author.setPlaceholderText(_translate("Dialog", "Please Enter Author"))
        self.lineEdit_publisher.setPlaceholderText(_translate("Dialog", "Please Enter Publisher"))
        self.pushButton_insertbook.setText(_translate("Dialog", "Insert Book"))

    def insert_book(self):
        def isEmpty(str):
            return bool(str)
        try:
            title = self.lineEdit_title.text()
            author = self.lineEdit_author.text()
            publisher = self.lineEdit_publisher.text()

            if not(isEmpty(title) and isEmpty(author) and isEmpty(publisher)):
                self.label_result.setText('Please Fill All Fields')
                self.label_result.setStyleSheet('color:red')
                return
            
            query = f"INSERT INTO `addbook` (`title`, `author`, `publisher`, `isAvilable`) VALUES('{title}', '{author}', '{publisher}', 1)"
            mycursor.execute(query)
            my_db.commit()
            
            self.label_result.setText("book add succesufly".capitalize())
            self.label_result.setStyleSheet('color:green')

            self.lineEdit_title.setText('')
            self.lineEdit_author.setText('')
            self.lineEdit_publisher.setText('')
             
        except mc.errors as e:
            self.label_result.setText("Faild To Add Book , DataBase Connection Error")
