# Form implementation generated from reading ui file 'AddMember.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc


my_db = mc.connect(
    host='localhost',
    user='root',
    password='',
    database='library'
)
my_cursor = my_db.cursor()

class member_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 250)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_mname = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mname.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_mname.setFont(font)
        self.lineEdit_mname.setObjectName("lineEdit_mname")
        self.verticalLayout.addWidget(self.lineEdit_mname)
        self.lineEdit_mmobile = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_mmobile.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_mmobile.setFont(font)
        self.lineEdit_mmobile.setObjectName("lineEdit_mmobile")
        self.verticalLayout.addWidget(self.lineEdit_mmobile)
        self.lineEdit_memail = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_memail.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_memail.setFont(font)
        self.lineEdit_memail.setObjectName("lineEdit_memail")
        self.verticalLayout.addWidget(self.lineEdit_memail)
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)

        #Add To DataBase
        self.pushButton_save.clicked.connect(self.insert_member)


        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"\n"
"background-color:gray;\n"
"color:white\n"
"\n"
"\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save)
        self.label_result = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.verticalLayout.addWidget(self.label_result)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Insert Member"))
        self.lineEdit_mname.setPlaceholderText(_translate("Dialog", "Please Enter Member Name"))
        self.lineEdit_mmobile.setPlaceholderText(_translate("Dialog", "Please Enter Member Mobile"))
        self.lineEdit_memail.setPlaceholderText(_translate("Dialog", "Please Enter Member Email"))
        self.pushButton_save.setText(_translate("Dialog", "Insert Member"))

    def insert_member(self):
        def isEmpty(str):
            return bool(str)
        try:
            name = self.lineEdit_mname.text()
            mail = self.lineEdit_memail.text()
            mobile = self.lineEdit_mmobile.text()

            if not(isEmpty(name) and isEmpty(mail) and isEmpty(mobile)):
                self.label_result.setText("please fill all fields".capitalize())
                self.label_result.setStyleSheet("color:red")
                return

            query = f"INSERT INTO `addmember`(`name` , `email` , `mobile`) VALUES ('{name}' , '{mail}' , '{mobile}')"
            my_cursor.execute(query)

            my_db.commit()

            self.label_result.setText("Member Add Successfly")
            self.label_result.setStyleSheet("colorLgreen")

            self.lineEdit_memail.setText('')
            self.lineEdit_mmobile.setText('')
            self.lineEdit_mname.setText('')

        except mc.errors as e:
            self.label_result.setText('Faild Too Add Data , DataBase Error')
            self.label_result.setStyleSheet('color:red')


